k9s:
  cluster: kind-kind-cluster
  namespace:
    active: crossplane-system
    lockFavorites: false
    favorites:
      - kyverno
      - trivy-system
      - flux-system
      - crossplane-system
      - kube-system
      - all
      - default
      - dapr-system
      - argocd
  view:
    active: v1/namespaces
  featureGates:
    nodeShell: false
  proxy: null
