k9s:
  cluster: AKS20LOCO100-P
  namespace:
    active: ns20rw100-p
    lockFavorites: false
    favorites:
      - ns20rv100-p
      - ns20loco100-p
      - maglev-operations
      - ns20rw100-p
      - maglev-operator
      - ns20rrp100-p
      - maglev-privateagent
      - ns20obf100-p
      - ns20ccmportal100-p
  view:
    active: contexts
  featureGates:
    nodeShell: false
  proxy: null
