k9s:
  cluster: AKS20LOCO100-P
  namespace:
    active: kube-system
    lockFavorites: false
    favorites:
      - kube-system
      - flux-system
      - ns20rpt100-p
      - ns20gvo100-p
      - ns20rit100-p
      - ns20vsmv100-p
      - ns20ccmportal100-p
      - ns20hijr100-p
      - ns20rv100-p
  view:
    active: contexts
  featureGates:
    nodeShell: false
  proxy: null
