k9s:
  cluster: AKS20CCMMAGLV100-DEV
  namespace:
    active: flux-system
    lockFavorites: false
    favorites:
      - crossplane-system
      - trivy-system
      - gatekeeper-system
      - flux-system
      - tigera-operator
      - calico-system
      - all
      - kube-system
      - kyverno
  view:
    active: contexts
  featureGates:
    nodeShell: false
  proxy: null
