k9s:
  cluster: AKS20CCMMAGLV100-DEV
  namespace:
    active: trivy-system
    lockFavorites: false
    favorites:
      - trivy-system
      - argocd
      - all
      - default
      - backstage
      - ns20loco100-ta
  view:
    active: aquasecurity.github.io/v1alpha1/vulnerabilityreports trivy-system
  featureGates:
    nodeShell: false
  proxy: null
