#!/usr/bin/env bash

# Colors taken from Catppuccin Mocha theme
red="0xfff38ba8" # Color Red: #f38ba8
blue="0xff89b4fa" # Color Blue: #89b4fa

options=(
	active_color="$red"
	inactive_color="$blue"
	hidpi=on
	style=round
	width=6.0
)

borders "${options[@]}"