k9s:
  cluster: k8s-ams-1-hostmeister
  namespace:
    active: adguard-home
    lockFavorites: false
    favorites:
      - adguard-home
      - all
      - argocd
      - cert-manager
      - kube-system
      - default
  view:
    active: v1/nodes
  featureGates:
    nodeShell: false
  proxy: null
