k9s:
  cluster: AKS20LOCO100-TA
  namespace:
    active: ns20cava100-ta
    lockFavorites: false
    favorites:
      - ns20cava100-ta
      - ns20cap100-ta
      - ns20netex100-ta
      - ns20ccmportal100-ta
      - ns20puls100-ta
      - nsco-akv2k8s
      - kube-system
      - ns20rpt100-ta
      - ns20abcv100-ta
  view:
    active: contexts
  featureGates:
    nodeShell: false
  proxy: null
