k9s:
  cluster: AKS20LOCO100-TA
  namespace:
    active: maglev-privateagent
    lockFavorites: false
    favorites:
      - ns20rv100-ta
      - maglev-privateagent
      - maglev-api
      - ns20rails100-ta
      - all
      - kube-system
      - ns20ccmportal100-ta
      - ns20loco100-ta
      - maglev-operations
  view:
    active: v1/pods maglev-privateagent
  featureGates:
    nodeShell: false
  proxy: null
